sudo: false

language: python
python: 3.7

cache: pip

script:
  - pip install -r requirements.txt

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true
    python: 3.7
